### ISSUE TITLE
Print functions syntaxis.

### ISSUE THREAD

**Issue by jfernandz** [bmenendez/20up#30]
I'm getting that message with all print functions. 

> python 20up.py 
>   File "20up.py", line 46
>     print '|'
>             ^
> SyntaxError: Missing parentheses in call to 'print'

**Comment by bmenendez** [comment]
Hi @WyRe,

This is because you are using python 3.x while 20up uses python 2.x. Anyway, the tool is no longer maintained since the social network has closed the ability to navigate through your account (see the wall, your pictures, etc.).

They provided an update in their app so you can download all your pictures and their comments ;-)

Kind regards,

Borja.
